# Generated by Django 5.2 on 2025-07-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_video_age_group_video_current_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='current_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
