# Generated by Django 5.2 on 2025-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_video_current_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='field_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='field_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
