upstream sportvid_dev_backend_gunicorn {
    # server 127.0.0.1:8001 fail_timeout=0;
    server backend:8001 fail_timeout=0;  # using docker service name
}

server { # sets up a default server to return “444 No Response” on an unrecognized host
    listen 80 default_server;
    
    server_name _;
    return 444;
}

server { # same for HTTPS, use dummy SSL certs for the default server
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/cert/dummy.crt;
    ssl_certificate_key /etc/cert/dummy.key;
    
    return 444;
}

server {
    listen 80;
    server_name dev.sportvid.dshs-koeln.de;
    return 301 https://$server_name$request_uri;
}

server {
    listen          443 ssl;

    ssl_certificate     /etc/cert/cert_bundle.pem;
    ssl_certificate_key /etc/cert/private_key;
    ssl_password_file   /etc/cert/password.txt;

    server_name     dev.sportvid.dshs-koeln.de;
    root            /app/frontend/dist/;

    client_max_body_size 4G; # is this a reasonable limit?
    keepalive_timeout 65;
    
    location /thumbnails/ {
        # alias /data/predictions/;
        alias /thumbnail/;
    }
    
    location /media/ {
        # alias /app/frontend/dist/media/;
        # alias /data/media/;
        alias /media/;
    }

    location /css/ {
        alias /app/frontend/dist/css/;
    }

    location /js/ {
        alias /app/frontend/dist/js/;
    }

    location /fonts/ {
        alias /app/frontend/dist/fonts/;
    }

    location /img/ {
        alias /app/frontend/dist/img/;
    }

    location ~ /\. {  # deny access to hidden files like .htaccess
        deny all;
    }
    
    location / {  # frontend fallback
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location @proxy_to_app {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_pass http://sportvid_dev_backend_gunicorn;
    }

    # location /api/ {
    #     proxy_pass http://localhost:8001/api/;
    # }

    location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_pass http://backend:8001/api/;  # uses docker service name
    }
}