version: "0.1"

networks:
  sportvid_dev:
    name: sportvid_dev_network

services:
    sportvidfrontend:
        image: sportvidfrontend
        networks:
          - sportvid_dev_network
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
          - ${FRONTEND_PORT}:${FRONTEND_PORT}
        volumes:
          - type: bind
            source: ./media
            target: /app/src/assets
