secrets:
  django_settings:
    file: ${SPORTVID_BACKEND_CONFIG}

# volumes:
#   assets:
#     name: frontend-assets
services:
  inference_ray:
    container_name: inference_ray
    build:
      context: .
      dockerfile: inference_ray/Dockerfile
    init: true
    shm_size: "2g" # TODO: should be 30% of total available memory?
    environment:
      - HF_HOME=/models
      - NUMBA_CACHE_DIR=/tmp
      # - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${DATA_PATH}/analyser:/data/
      - ${DATA_PATH}/media/:/media/
      - ${DATA_PATH}/models/:/models/
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    working_dir: /app/
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    command:
      - "uv"
      - "run"
      - "--package"
      - "inference_ray"
      - "serve"
      - "run"
      - "/app/inference_ray/deploy.yml"

  analyser:
    container_name: analyser
    build:
      context: .
    volumes:
      - ${DATA_PATH}/analyser:/data/
      - ${DATA_PATH}/media/:/media/
      - ${DATA_PATH}/models/:/models/
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    working_dir: /app/
    command: uv run --package analyser analyser/src/analyser/server.py -v -c analyser/config.yml

  memcached:
    container_name: memcached
    image: memcached:1.6.10-buster
    command: -I 32m

  valkey:
    container_name: valkey
    image: valkey/valkey:8.1.1-alpine
    command:
      - "/usr/local/bin/valkey-server"
      - "--bind"
      - "${VALKEY_INTERNAL_HOST}"
      - "--port"
      - "${VALKEY_INTERNAL_PORT}"
      # - "--requirepass"
      # - "${VALKEY_PASSWD}"
      # - "--protected-mode"
      # - "yes"
    ports:
      - ${VALKEY_INTERNAL_PORT}:${VALKEY_INTERNAL_PORT} # remap port

  postgres:
    container_name: postgres
    image: postgres:14.17
    environment:
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_PASSWORD
    volumes:
      - ${DATA_PATH}/shared/db/:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d  # init.sh is invoked automatically
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  celery:
    container_name: celery
    build:
      context: .
    secrets:
      - django_settings
    volumes:
      - ${DATA_PATH}/media/:/media
      - ${DATA_PATH}/predictions:/predictions
      - ${DATA_PATH}/backend_cache:/cache
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend/:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    depends_on:
      - postgres
      - valkey
    tmpfs:
      - /tmp
      - /var
    working_dir: /app/backend/src/backend/
    command:
      - "uv"
      - "run"
      - "--package"
      - "backend"
      - "celery"
      - "-A"
      - "sportvid"
      - "worker"
      - "--loglevel"
      - "${LOG_LEVEL:-DEBUG}"

  backend:
    container_name: backend
    build:
      context: .
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    secrets:
      - django_settings
    environment:
      - PYTHONPATH=/app/backend/:/app:/app/analyser:/app/backend/src/backend/
    volumes:
      - ${DATA_PATH}/media/:/media
      - ${DATA_PATH}/predictions:/predictions
      - ${DATA_PATH}/backend_cache:/cache
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend/:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    tmpfs:
      - /tmp
      - /var/tmp
    working_dir: /app/
    command:
      - "uv"
      - "run"
      - "--package"
      - "backend"
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:${BACKEND_PORT}"
      - "--env"
      - "SCRIPT_NAME=/api"
      - "sportvid.wsgi"
      - "--capture-output"
      - "--log-level"
      - "${LOG_LEVEL:-DEBUG}"
      - "--timeout"
      - "1800"
      - "--workers"
      - "${GUNICORN_WORKERS:-4}"
    # command: uv run --package backend python3 backend/src/backend/manage.py runserver 0.0.0.0:8000
    depends_on:
      # NOTE: could use a sleep script until PSQL is reachable (see /postgres/wait.sh)
      # postgres:
      #  condition: service_healthy
      memcached:
        condition: service_started
      celery:
        condition: service_started

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - ./frontend/:/app/frontend
      - ${DATA_PATH}/predictions/:/thumbnails
      - ${DATA_PATH}/media/:/media
      # - assets:/assets
    working_dir: /app/frontend

