networks:
  shared:
    external: true
  prod:
    driver: bridge

secrets:
  django_settings:
    file: ${SPORTVID_BACKEND_CONFIG}

services:
  inference_ray:
    container_name: inference_ray_prod
    build:
      context: .
    environment:
      - HF_HOME=/models
      - NUMBA_CACHE_DIR=/tmp
      - NVIDIA_VISIBLE_DEVICES=all
      - BACKEND_PORT=${BACKEND_PORT} # TODO: not working ???
    env_file:
      - /opt/deploy/.env.prod
    volumes:
      - ${DATA_PATH}/analyser:/data/
      - ${DATA_PATH}/media/:/media/
      - ${DATA_PATH}/models/:/models/
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    working_dir: /app/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # TODO: GPU usage for prod/dev ???
              # count: all
              count: 2
              capabilities: [gpu]
    command:
      - "uv"
      - "run"
      - "--package"
      - "inference_ray"
      - "serve"
      - "run"
      - "/app/inference_ray/deploy.cuda.yml"
    networks:
      - prod

  analyser:
    container_name: analyser_prod
    build:
      context: .
    env_file:
      - /opt/deploy/.env.prod
    volumes:
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ${DATA_PATH}/analyser:/data/
      - ${DATA_PATH}/media/:/media/
      - ${DATA_PATH}/cache/:/cache/
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    working_dir: /app/
    command: uv run --package analyser analyser/src/analyser/server.py -v -c analyser/config.yml
    networks:
      - prod

  memcached:
    container_name: memcached_prod
    image: memcached:1.6.10-buster
    command: -I 32m
    networks:
      - prod

  valkey:
    container_name: valkey_prod
    image: valkey/valkey:8.1.1-alpine
    command: /usr/local/bin/valkey-server --port ${VALKEY_PORT} --bind 0.0.0.0
    ports:
      - "127.0.0.1:${VALKEY_PORT}:${VALKEY_PORT}"
    networks:
      - prod

  celery:
    container_name: celery_prod
    build:
      context: .
    env_file:
      - /opt/deploy/.env.prod
    volumes:
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend/:/app/backend
      - ${DATA_PATH}/media/:/media
      - ${DATA_PATH}/predictions:/predictions
      - ${DATA_PATH}/backend_cache:/cache
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    tmpfs:
      - /tmp
      - /var/tmp
    working_dir: /app/backend/src/backend/
    depends_on:
      - postgres
    

    command:
      - "uv"
      - "run"
      - "--package"
      - "backend"
      - "celery"
      - "-A"
      - "sportvid"
      - "worker"
      - "--loglevel"
      - "INFO"
    networks:
      - shared
      - prod

  backend:
    container_name: backend_prod
    build:
      context: .
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    secrets:
      - django_settings
    environment:
      - PYTHONPATH=/app/backend/:/app:/app/analyser:/app/backend/src/backend/
    env_file:
     - /opt/deploy/.env.prod
    volumes:
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend/:/app/backend
      - ${DATA_PATH}/media/:/media
      - ${DATA_PATH}/predictions:/predictions
      - ${DATA_PATH}/backend_cache:/cache
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    tmpfs:
      - /tmp
      - /var/tmp
    working_dir: /app/
    command:
      - "uv"
      - "run"
      - "--package"
      - "backend"
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:${BACKEND_PORT}"
      - "--env"
      - "SCRIPT_NAME=/api"
      - "sportvid.wsgi"
      - "--capture-output"
      - "--log-level"
      - "${LOG_LEVEL}"
      - "--workers=${GUNICORN_WORKERS}"
    depends_on:
      - postgres
      - memcached
      - celery
    networks:
      - shared
      - prod

  frontend:
    container_name: frontend_prod
    build:
      context: ./frontend
    volumes:
      # - ./frontend/:/app/frontend
      # - ${DATA_PATH}/predictions/:/thumbnails
      # - ${DATA_PATH}/media/:/media
      - assets:/assets
    command: sh -c 'mkdir -p /assets/prod && cp -r dist/* /assets/prod/'
    networks:
      - shared
      - prod

  postgres:
    container_name: postgres
    image: postgres:14.17
    volumes:
      - /mnt/data/shared/db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - shared