services:
  inference_ray:
    build:
      context: .
    init: true
    shm_size: "2g" # TODO: should be 30% of total available memory?
    environment:
      - HF_HOME=/models
      - NUMBA_CACHE_DIR=/tmp
      - NVIDIA_VISIBLE_DEVICES=all
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./data/analyser:/data/
      - ./data/media/:/media/
      - ./data/models/:/models/
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    working_dir: /app/
    command:
      - "uv"
      - "run"
      - "--package"
      - "inference_ray"
      - "serve"
      - "run"
      - "/app/inference_ray/deploy.cuda.yml"

  analyser:
    image: ghcr.io/astral-sh/uv:debian
    volumes:
      - .data/analyser:/data/
      - .data/media/:/media/
      - .data/cache/:/cache/
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    working_dir: /app/
    command: uv run --package analyser analyser/src/analyser/server.py -v -c analyser/config.yml

  postgres:
    image: postgres:14.17
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tibava
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  memcached:
    image: memcached:1.6.10-buster
    command: -I 32m

  valkey:
    image: valkey/valkey:8.1.1-alpine
    command: /usr/local/bin/valkey-server --port 6380 --bind 0.0.0.0
    ports:
      - "127.0.0.1:6380:6380"

  celery:
    build:
      context: .
    volumes:
      - .data/media/:/media
      - .data/predictions:/predictions
      - .data/backend_cache:/cache
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend/:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    tmpfs:
      - /tmp
      - /var
    working_dir: /app/backend/src/backend/
    environment:
      - SPORTVID_BACKEND_CONFIG=/app/backend/config.json
    command:
      - "uv"
      - "run"
      - "--package"
      - "backend"
      - "celery"
      - "-A"
      - "sportvid"
      - "worker"
      - "--loglevel"
      - "INFO"

  backend:
    build:
      context: .
      args:
        - BACKEND_PORT=8000
    ports:
      - 8000:8000
    environment:
      - PYTHONPATH=/app/backend/:/app:/app/analyser:/app/backend/src/backend/
      - SPORTVID_BACKEND_CONFIG=/app/backend/config.json
    volumes:
      - .data/media/:/media
      - .data/predictions:/predictions
      - .data/backend_cache:/cache
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend/:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    tmpfs:
      - /tmp
      - /var/tmp
    working_dir: /app/
    command:
      - "uv"
      - "run"
      - "--package"
      - "backend"
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:${BACKEND_PORT}"
      - "--env"
      - "SCRIPT_NAME=/api"
      - "sportvid.wsgi"
      - "--capture-output"
      - "--log-level"
      - "${LOG_LEVEL}"
      - "--timeout"
      - "1800"
      - "--workers=${GUNICORN_WORKERS}"
    # command: uv run --package backend python3 backend/src/backend/manage.py runserver 0.0.0.0:8000
    depends_on:
      # NOTE: could use a sleep script until PSQL is reachable (see /postgres/wait.sh)
      # postgres:
      #   condition: service_healthy
      memcached:
        condition: service_started
      celery:
        condition: service_started

  frontend:
    image: frontend
    ports:
      - 8080:8080
      - 80:80
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/app/frontend
      - .data/predictions/:/thumbnails
      - .data/media/:/media
      - assets:/assets
    working_dir: /app/frontend