networks:
  shared:
    external: true
  prod:
    driver: bridge

secrets:
  django_settings:
    file: ${SPORTVID_BACKEND_CONFIG}

volumes:
  assets:
    external: true
    name: frontend-assets

services:
  inference_ray:
    container_name: inference_ray_prod
    build:
      context: .
    init: true
    shm_size: "12g" # TODO: should be 30% of total available memory?
    environment:
      - HF_HOME=/models
      - NUMBA_CACHE_DIR=/tmp
      - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - /opt/deploy/.env.prod
    volumes:
      - ${DATA_PATH}/analyser:/data/
      - ${DATA_PATH}/media/:/media/
      - ${DATA_PATH}/models/:/models/
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    working_dir: /app/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 3
              capabilities: [gpu]
    command:
      - "uv"
      - "run"
      - "--package"
      - "inference_ray"
      - "serve"
      - "run"
      - "/app/inference_ray/deploy.cuda.yml"
    networks:
      - prod

  analyser:
    container_name: analyser_prod
    build:
      context: .
    env_file:
      - /opt/deploy/.env.prod
    volumes:
      - ${DATA_PATH}/analyser:/data/
      - ${DATA_PATH}/media/:/media/
      - ${DATA_PATH}/cache/:/cache/
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    working_dir: /app/
    command: uv run --package analyser analyser/src/analyser/server.py -v -c analyser/config.yml
    networks:
      - prod

  memcached:
    container_name: memcached_prod
    image: memcached:1.6.10-buster
    command: -I 32m
    networks:
      - prod

  valkey:
    container_name: valkey_prod
    image: valkey/valkey:8.1.1-alpine
    env_file: 
      - /opt/deploy/.env.prod
    command:
      - "/usr/local/bin/valkey-server"
      - "--bind"
      - "${VALKEY_INTERNAL_HOST}"
      - "--port"
      - "${VALKEY_INTERNAL_PORT}"
      - "--requirepass"
      - "${VALKEY_PASSWD}"
      - "--protected-mode"
      - "yes"
    ports:
      - ${VALKEY_INTERNAL_PORT}:${VALKEY_INTERNAL_PORT}  # remap valkey port
    networks:
      - prod

  celery:
    container_name: celery_prod
    build:
      context: .
    env_file:
      - /opt/deploy/.env.prod
    volumes:
      - ${DATA_PATH}/media/:/media
      - ${DATA_PATH}/predictions:/predictions
      - ${DATA_PATH}/backend_cache:/cache
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend/:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    tmpfs:
      - /tmp
      - /var/tmp
    working_dir: /app/backend/src/backend/
    # NOTE: could use a sleep script until PSQL is reachable (see /postgres/wait.sh)
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    command:
      - "uv"
      - "run"
      - "--package"
      - "backend"
      - "celery"
      - "-A"
      - "sportvid"
      - "worker"
      - "--loglevel"
      - "${LOG_LEVEL:-INFO}"
    networks:
      - shared
      - prod

  backend:
    container_name: backend_prod
    build:
      context: .
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    secrets:
      - django_settings
    environment:
      - PYTHONPATH=/app/backend/:/app:/app/analyser:/app/backend/src/backend/
    env_file:
      - /opt/deploy/.env.prod
    volumes:
      - ${DATA_PATH}/media/:/media
      - ${DATA_PATH}/predictions:/predictions
      - ${DATA_PATH}/backend_cache:/cache
      - ./inference_ray:/app/inference_ray
      - ./analyser:/app/analyser
      - ./packages:/app/packages
      - ./backend/:/app/backend
      - ./pyproject.toml:/app/pyproject.toml
      - ./.python-version:/app/.python-version
    tmpfs:
      - /tmp
      - /var/tmp
    working_dir: /app/
    command:
      - "uv"
      - "run"
      - "--package"
      - "backend"
      - "gunicorn"
      - "--bind"
      - "0.0.0.0:${BACKEND_PORT}"
      - "--env"
      - "SCRIPT_NAME=/api"
      - "sportvid.wsgi"
      - "--capture-output"
      - "--log-level"
      - "${LOG_LEVEL:-INFO}"
      - "--timeout"
      - "${GUNICORN_TIMEOUT:-1800}"
      - "--workers"
      - "${GUNICORN_WORKERS:-16}"
    depends_on:
      # NOTE: could use a sleep script until PSQL is reachable (see /postgres/wait.sh)
      # postgres:
      #   condition: service_healthy
      memcached:
        condition: service_started
      celery:
        condition: service_started
    networks:
      - shared
      - prod

  frontend:
    container_name: frontend_prod
    build:
      context: ./frontend
    volumes:
      # - ./frontend/:/app/frontend
      # - ${DATA_PATH}/predictions/:/thumbnails
      # - ${DATA_PATH}/media/:/media
      - assets:/assets
    command: sh -c 'mkdir -p /assets/prod && cp -r dist/* /assets/prod/'
    networks:
      - shared
      - prod
