# Generated by Django 5.1.7 on 2025-03-21 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20240507_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS'), ('B', 'BBOXES')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
