# Generated by Django 5.2.4 on 2025-07-22 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_calibrationassets_pointcorrespondence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS'), ('B', 'BBOXES'), ('P', 'POSS')], default='S', max_length=2),
        ),
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('file', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('ext', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
