# Generated by Django 5.2 on 2025-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_pluginrunresult_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='age_group',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='current_position',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='division',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='field_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='field_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='total_number_of_teams',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
