# Generated by Django 5.2.4 on 2025-08-13 21:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_sportviduser_max_file_size_alter_sportviduser_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='meta_ext',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='meta_file',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
