# Generated by Django 5.2.4 on 2025-08-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_trackingdata_ext_alter_trackingdata_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS'), ('B', 'BBOXES'), ('P', 'POS'), ('FL', 'FL')], default='S', max_length=2),
        ),
    ]
