# Generated by Django 5.2.4 on 2025-09-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_pluginrunresult_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video'),
        ),
    ]
