# Generated by Django 5.2.4 on 2025-09-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_trackingdata_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcorrespondence',
            name='set',
            field=models.BooleanField(default=False),
        ),
    ]
