# Generated by Django 5.2.4 on 2025-12-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_pointcorrespondence_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointcorrespondence',
            name='compAreaCoord_x',
        ),
        migrations.RemoveField(
            model_name='pointcorrespondence',
            name='compAreaCoord_y',
        ),
        migrations.RemoveField(
            model_name='pointcorrespondence',
            name='compAreaCoord_z',
        ),
        migrations.RemoveField(
            model_name='pointcorrespondence',
            name='videoCoord_x',
        ),
        migrations.RemoveField(
            model_name='pointcorrespondence',
            name='videoCoord_y',
        ),
        migrations.RemoveField(
            model_name='pointcorrespondence',
            name='videoCoord_z',
        ),
        migrations.AddField(
            model_name='calibrationassets',
            name='object_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='pointcorrespondence',
            name='comp_area_coords_rel',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pointcorrespondence',
            name='video_coords_rel',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pointcorrespondence',
            name='calibration_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_data', to='backend.calibrationassets'),
        ),
    ]
