# Generated by Django 5.2.4 on 2026-01-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_sportviduser_max_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportviduser',
            old_name='allowance',
            new_name='video_allowance',
        ),
        migrations.AddField(
            model_name='sportviduser',
            name='file_allowance',
            field=models.IntegerField(default=40),
        ),
    ]
