# Generated by Django 5.2.4 on 2026-02-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_sportviduser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportviduser',
            name='file_allowance',
        ),
        migrations.RemoveField(
            model_name='sportviduser',
            name='video_allowance',
        ),
        migrations.AddField(
            model_name='sportviduser',
            name='storage_size',
            field=models.BigIntegerField(default=107374182400),
        ),
        migrations.AddField(
            model_name='sportviduser',
            name='used_storage_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
