# Generated by Django 5.2.4 on 2026-03-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_alter_pluginrunresult_type'),
    ]

    operations = [
    ]
