data:
  data_dir: /data
  cache:
      type: valkey
      params:
        db: 1
        host: ${VALKEY_CLIENT_HOST}
        port: ${VALKEY_INTERNAL_PORT}
        password: ${VALKEY_PASSWD}
        tag: analyser
inference:
  type: ray
  params: 
    host: inference_ray
    port: ${BACKEND_PORT}
    status_port: ${INFERENCE_RAY_STATUS_PORT}
