data:
  data_dir: /data
  cache:
      type: valkey
      params:
        db: 1
        host: valkey
        port: ${VALKEY_PORT}
        tag: analyser
inference:
  type: ray
  params: 
    host: inference_ray
    port: ${BACKEND_PORT}
    status_port: ${INFERENCE_RAY_STATUS_PORT}
