#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$PROD_DB_USER" WITH PASSWORD '$PROD_DB_PASSWD';
    CREATE USER "$DEV_DB_USER" WITH PASSWORD '$DEV_DB_PASSWD';
    CREATE DATABASE "$PROD_DB";
    CREATE DATABASE "$DEV_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$PROD_DB" TO "$PROD_DB_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$DEV_DB" TO "$DEV_DB_USER";
EOSQL