# Generated by Django 5.2.4 on 2026-06-17 13:49
import backend.models
import django.contrib.auth.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid

from django.conf import settings
from django.db import migrations, models
from functools import lru_cache

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# backend.migrations.0018_auto_20240213_0903_squashed_0020_auto_20240216_1213
def remove_cluster_items_flagged_deleted(apps, schema_editor):
    ClusterItem = apps.get_model('backend', 'ClusterItem')
    ClusterItem.objects.filter(deleted=True).delete()

def populate_cluster_item_fields(apps, schema_editor):
    ClusterItem = apps.get_model('backend', 'ClusterItem')
    for item in (ClusterItem.objects.all()
                                    .select_related('plugin_run_result__plugin_run')
                                    .order_by('-plugin_run_result__plugin_run__date',
                                              'plugin_run_result__id')):
        try:
            data = get_data(item.plugin_run_result.data_id)
        except AttributeError as e:
            print(e)
            continue
        for cluster in data.clusters:
            if cluster.id == item.cluster_timeline_item.cluster_id.hex:
                break
        else:
            raise Exception('Cluster not found')
        item.embedding_id = cluster.embedding_ids[item.embedding_index]
        if item.embedding_id in cluster.sample_embedding_ids:
            item.is_sample = True

        image_id =  item.image_path.split('/')[-1].removesuffix('.jpg')

        run_result = (item.plugin_run_result
                          .plugin_run
                          .results
                          .filter(type='I')
                          .first())
        try:
            data = get_data(run_result.data_id)
        except AttributeError as e:
            print(e)
            continue
        for image in data.images:
            if image.id == image_id:
                item.time = image.time
                item.delta_time = image.delta_time
                break

        item.save()

@lru_cache(100)
def get_data(data_id):
    from data import DataManager
    data_manager = DataManager('/predictions')
    data = data_manager.load(data_id)
    with data:
        return data


class Migration(migrations.Migration):

    replaces = [('backend', '0001_initial'), ('backend', '0002_auto_20230629_1351'), ('backend', '0003_auto_20230718_1222'), ('backend', '0004_clustertimelineitem'), ('backend', '0005_clustertimelineitem_video'), ('backend', '0006_auto_20230803_1142'), ('backend', '0007_face'), ('backend', '0008_face_image_path'), ('backend', '0009_clustertimelineitem_plugin_run'), ('backend', '0010_auto_20230823_0856'), ('backend', '0011_auto_20231204_2019'), ('backend', '0012_auto_20240122_1541'), ('backend', '0013_auto_20240122_1549'), ('backend', '0014_auto_20240122_2009'), ('backend', '0015_auto_20240208_0958'), ('backend', '0016_auto_20240212_1359'), ('backend', '0017_auto_20240215_0910'), ('backend', '0018_auto_20240213_0903_squashed_0020_auto_20240216_1213'), ('backend', '0019_timeline_colormap_inverse'), ('backend', '0020_remove_clusteritem_plugin_item_ref'), ('backend', '0021_videoanalysisstate'), ('backend', '0022_auto_20240507_0815'), ('backend', '0023_alter_pluginrunresult_type_alter_video_file'), ('backend', '0024_calibrationassets_pointcorrespondence'), ('backend', '0025_alter_pluginrunresult_type_trackingdata'), ('backend', '0026_alter_pluginrunresult_type'), ('backend', '0027_video_age_group_video_current_position_and_more'), ('backend', '0028_alter_video_current_position'), ('backend', '0029_alter_video_field_length_alter_video_field_width'), ('backend', '0030_sportviduser_max_file_size_alter_sportviduser_allowance_and_more'), ('backend', '0031_trackingdata_meta_ext_trackingdata_meta_file'), ('backend', '0032_alter_trackingdata_ext_alter_trackingdata_file_type_and_more'), ('backend', '0033_alter_pluginrunresult_type'), ('backend', '0034_trackingdata_video'), ('backend', '0035_pointcorrespondence_set'), ('backend', '0036_remove_pointcorrespondence_compareacoord_x_and_more'), ('backend', '0037_alter_sportviduser_max_file_size'), ('backend', '0038_rename_allowance_sportviduser_video_allowance_and_more'), ('backend', '0039_video_status'), ('backend', '0040_sportviduser_role'), ('backend', '0041_remove_sportviduser_file_allowance_and_more'), ('backend', '0042_rename_storage_size_sportviduser_max_storage_size'), ('backend', '0043_trackingdata_file_size_trackingdata_meta_file_size_and_more'), ('backend', '0044_rename_template_calibrationassets_sport'), ('backend', '0045_alter_pluginrunresult_type'), ('backend', '0046_merge_20260330_1748')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportVidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('allowance', models.IntegerField(default=10)),
                ('max_video_size', models.BigIntegerField(default=524288000)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('color', models.CharField(default=backend.models.random_color_string, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PluginRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=256)),
                ('progress', models.FloatField(default=0.0)),
                ('in_scheduler', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('U', 'UNKNOWN'), ('E', 'ERROR'), ('D', 'DONE'), ('R', 'RUNNING'), ('Q', 'QUEUED'), ('W', 'WAITING')], default='U', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PluginRunResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('data_id', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS')], default='S', max_length=2)),
                ('plugin_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pluginrun')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('A', 'ANNOTATION'), ('R', 'PLUGIN_RESULT')], default='A', max_length=2)),
                ('order', models.IntegerField(default=-1)),
                ('collapse', models.BooleanField(default=False)),
                ('visualization', models.CharField(choices=[('C', 'COLOR'), ('CC', 'CATEGORY_COLOR'), ('SC', 'SCALAR_COLOR'), ('SL', 'SCALAR_LINE'), ('H', 'HIST')], default='C', max_length=2)),
                ('colormap', models.CharField(blank=True, max_length=256, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.timeline')),
                ('plugin_run_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.pluginrunresult')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=256, null=True)),
                ('start', models.FloatField(default=0)),
                ('end', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('ext', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineSegmentAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.annotation')),
                ('timeline_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timelinesegment')),
            ],
        ),
        migrations.AddField(
            model_name='timelinesegment',
            name='annotations',
            field=models.ManyToManyField(through='backend.TimelineSegmentAnnotation', to='backend.annotation'),
        ),
        migrations.AddField(
            model_name='timelinesegment',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timeline'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.video'),
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256, null=True)),
                ('keys', models.JSONField(null=True)),
                ('keys_string', models.CharField(max_length=256, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
        migrations.AddField(
            model_name='pluginrun',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.video'),
        ),
        migrations.CreateModel(
            name='AnnotationShortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.annotation')),
                ('shortcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shortcut')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('color', models.CharField(default=backend.models.random_color_string, max_length=256)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.annotationcategory'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video'),
        ),
        migrations.CreateModel(
            name='ClusterTimelineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('A', 'FACE'), ('P', 'PLACE')], default='A', max_length=2)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
                ('plugin_run', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.pluginrun')),
            ],
        ),
        migrations.AlterModelOptions(
            name='timelinesegment',
            options={'ordering': ['start']},
        ),
        migrations.CreateModel(
            name='ClusterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_item_ref', models.UUIDField()),
                ('embedding_index', models.PositiveIntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('image_path', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('A', 'FACE'), ('P', 'PLACE')], default='A', max_length=2)),
                ('cluster_timeline_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clustertimelineitem')),
                ('plugin_run_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_items', to='backend.pluginrunresult')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
        migrations.RunPython(
            code=remove_cluster_items_flagged_deleted,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='clusteritem',
            name='delta_time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusteritem',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clusteritem',
            name='time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clusteritem',
            name='cluster_timeline_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.clustertimelineitem'),
        ),
        migrations.RemoveField(
            model_name='clusteritem',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='type',
            field=models.CharField(choices=[('A', 'ANNOTATION'), ('R', 'PLUGIN_RESULT'), ('T', 'TRANSCRIPT')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='clusteritem',
            name='embedding_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pluginrunresult',
            name='plugin_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='backend.pluginrun'),
        ),
    migrations.RunPython(
        code=populate_cluster_item_fields,
        reverse_code=django.db.migrations.operations.special.RunPython.noop,
    ),
        migrations.RemoveField(
            model_name='clusteritem',
            name='embedding_index',
        ),
        migrations.AddField(
            model_name='timeline',
            name='colormap_inverse',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='clusteritem',
            name='plugin_item_ref',
        ),
        migrations.CreateModel(
            name='VideoAnalysisState',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.video')),
                ('selected_shots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.timeline')),
                ('selected_face_clustering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_analyses_state_face_clustering', to='backend.pluginrun')),
                ('selected_place_clustering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_analyses_state_place_clustering', to='backend.pluginrun')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.CreateModel(
            name='CalibrationAssets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('homography_matrix', models.JSONField(default=backend.models.default_homography_matrix)),
                ('sport', models.CharField(max_length=1024, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
                ('object_type', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='age_group',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='division',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='total_number_of_teams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='current_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='field_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='field_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportviduser',
            name='max_file_size',
            field=models.BigIntegerField(default=5368709120),
        ),
        migrations.RenameField(
            model_name='sportviduser',
            old_name='allowance',
            new_name='video_allowance',
        ),
        migrations.RemoveField(
            model_name='sportviduser',
            name='video_allowance',
        ),
        migrations.AlterField(
            model_name='sportviduser',
            name='max_video_size',
            field=models.BigIntegerField(default=5368709120),
        ),
        migrations.CreateModel(
            name='PointCorrespondence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('active', models.BooleanField(default=False)),
                ('calibration_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_data', to='backend.calibrationassets')),
                ('set', models.BooleanField(default=False)),
                ('comp_area_coords_rel', models.JSONField(default=list)),
                ('video_coords_rel', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('P', 'PROCESSING'), ('D', 'DONE'), ('E', 'ERROR')], default='D', max_length=2),
        ),
        migrations.AddField(
            model_name='sportviduser',
            name='role',
            field=models.CharField(default='user', max_length=256),
        ),
        migrations.AddField(
            model_name='sportviduser',
            name='used_storage_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sportviduser',
            name='max_storage_size',
            field=models.BigIntegerField(default=107374182400),
        ),
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('file', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('ext', models.CharField(default='', max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(default='', max_length=256)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meta_ext', models.CharField(default='', max_length=256)),
                ('meta_file', models.UUIDField(blank=True, null=True)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
                ('file_size', models.BigIntegerField(default=0)),
                ('meta_file_size', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS'), ('B', 'BBOXES'), ('P', 'POS'), ('FL', 'FL'), ('KI', 'KPI')], default='S', max_length=2),
        ),
    ]
