# Generated by Django 5.2.4 on 2025-08-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_video_field_length_alter_video_field_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibavauser',
            name='max_file_size',
            field=models.BigIntegerField(default=10737418240),
        ),
        migrations.AlterField(
            model_name='tibavauser',
            name='allowance',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='tibavauser',
            name='max_video_size',
            field=models.BigIntegerField(default=5368709120),
        ),
    ]
