# Generated by Django 5.2.4 on 2025-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_trackingdata_meta_ext_trackingdata_meta_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdata',
            name='ext',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='file_type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='meta_ext',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='meta_file',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
