# Generated by Django 5.2.4 on 2026-01-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_pointcorrespondence_compareacoord_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportviduser',
            name='max_file_size',
            field=models.BigIntegerField(default=5368709120),
        ),
    ]
