# Generated by Django 5.2.4 on 2026-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_rename_allowance_tibavauser_video_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('P', 'PROCESSING'), ('D', 'DONE'), ('E', 'ERROR')], default='D', max_length=2),
        ),
    ]
