# Generated by Django 5.2.4 on 2026-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibavauser',
            name='role',
            field=models.CharField(default='user', max_length=256),
        ),
    ]
