# Generated by Django 5.2.4 on 2026-02-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_remove_sportviduser_file_allowance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportviduser',
            old_name='storage_size',
            new_name='max_storage_size',
        ),
    ]
