# Generated by Django 5.2.4 on 2026-02-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_rename_storage_size_tibavauser_max_storage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='meta_file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
