# Generated by Django 5.2.4 on 2026-02-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_trackingdata_file_size_trackingdata_meta_file_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationassets',
            old_name='template',
            new_name='sport',
        ),
    ]
