# Generated by Django 5.2.4 on 2026-03-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_rename_template_calibrationassets_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sport',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
