# Generated by Django 5.2.4 on 2026-02-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_video_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS'), ('B', 'BBOXES'), ('P', 'POS'), ('FL', 'FL'), ('KPI', 'KPI')], default='S', max_length=2),
        ),
    ]
