# Generated by Django 5.2.4 on 2026-03-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_video_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointcorrespondence',
            name='set',
        ),
    ]
