# Generated by Django 5.2.4 on 2026-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_trackingdata_delimiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='asset_dir',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='manifest_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='media_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='age_group',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='division',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='sport',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
