# Generated by Django 5.2.4 on 2026-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_video_asset_dir_video_manifest_path_video_media_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='task_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
