# Generated by Django 5.2.4 on 2026-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_video_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('TL', 'LIST'), ('TD', 'DICT'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS'), ('B', 'BBOXES'), ('P', 'POS'), ('FL', 'FL'), ('KPI', 'KPI'), ('NPY', 'NPY'), ('RID', 'RID')], default='S', max_length=3),
        ),
    ]
