# Generated by Django 5.2.4 on 2026-07-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_alter_pluginrunresult_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrun',
            name='calibration_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_runs', to='backend.calibrationassets'),
        ),
        migrations.AddField(
            model_name='pluginrun',
            name='source_plugin_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_plugin_runs', to='backend.pluginrun'),
        ),
        migrations.AddField(
            model_name='pluginrun',
            name='tracking_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_runs', to='backend.trackingdata'),
        ),
    ]
