# Generated by Django 5.2.4 on 2026-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_alter_pluginrunresult_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportviduser',
            name='dashboard_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
