# Generated by Django 5.2.4 on 2026-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_sportviduser_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportviduser',
            name='video_view_mode',
            field=models.CharField(blank=True, default='grid', max_length=16),
        ),
    ]
