# Generated by Django 5.2.4 on 2026-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_sportviduser_video_view_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportviduser',
            name='experience_mode',
            field=models.CharField(blank=True, default='complex', max_length=16),
        ),
    ]
