# Generated by Django 5.2.4 on 2026-08-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_sportviduser_experience_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
