# Generated by Django 5.2.4 on 2026-08-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_video_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrun',
            name='task_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
