# Generated by Django 5.2.4 on 2026-08-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_pluginrun_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrun',
            name='eta_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='eta_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pluginrun',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
