[project]
name = "inference_ray"
version = "0.1.0"
description = "inference server package"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "interface",
    "data",
    "utils",
    "grpcio>=1.70.0",
    "grpcio-tools==1.70.0",
    "imageio>=2.37.0",
    "msgpack>=1.1.0",
    "packaging>=24.2",
    "pip>=25.0.1",
    "protobuf>=5.29.3",
    "requests>=2.32.3",
    "numpy>=2.1.1",
    "torchvision",
    "pandas>=2.0.0",
    "tqdm>=4.67.1",
    "transformers>=4.48.3",
    "valkey>=6.1.0",
    "h5py>=3.12.1",
    "imageio[ffmpeg,pyav]>=2.37.0",
    "librosa>=0.11.0",
    "onnx>=1.17.0",
    "onnxruntime-gpu>=1.13.1",
    "onnx-simplifier>=0.3.5",
    "onnxruntime-gpu>=1.21.1",
    "qdrant-client>=1.13.2",
    "ray[serve,serve-grpc]",
    "scipy>=1.15.2",
    "scikit-learn>=1.6.1",
    "opencv-python-headless>=4.11.0.86",
    "floodlight==1.1.0",
    "lap",
    "motmetrics",
    "filterpy",
    "tabulate",
    "ninja",
    "thop",
    "Pillow",
    "loguru",
    "scikit-image",
    "ultralytics>=8.0",
    "rfdetr",
    "torchreid",
    "click==8.2.1"
]

[tool.uv]
package = true
# no-build-isolation-package = [ "torch" ]
# pip-install-args = [
#    "--no-build-isolation"
# ]

[project.optional-dependencies]
tracking = [
     "bytetrack",
]

[tool.uv.sources]
interface = { workspace = true }
data = { workspace = true }
utils = { workspace = true }
bytetrack = { path = "third_party/ByteTrack" }