name: deploy_prod

on:
  push:
    branches:
      - deploy-prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Restart prod systemd service
        run: |
          systemctl restart sportvid_prod
