name: Deploy DEV (via systemctl)

on:
  push:
    branches:
      - deploy-dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Restart dev systemd service
        run: |
          systemctl restart sportvid_dev
